version: '3.8'

services:
  db:
     image: postgres
     environment:
        POSTGRES_USER: <username>
        POSTGRES_PASSWORD: <password>
        POSTGRES_DB: TEST_SM
     volumes:
        - postgres_data:/var/lib/postgresql/data
     ports:
        - "5432:5432"
     restart: unless-stopped

  pgAdmin:
     image: dpage/pgadmin4
     depends_on:
        - db
     environment:
        PGADMIN_DEFAULT_EMAIL: <name@example.com>
        PGADMIN_DEFAULT_PASSWORD: <password>
     ports:
        - "82:80"
     restart: unless-stopped

  flask_app:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Der Name deiner Dockerfile, falls er nicht standardmäßig 'Dockerfile' heißt
    image: agent_backend # Wenn image auch auf Docker-Hub hochgeladen werden soll: <Docker-Hub-Username>/agent_backend
    ports:
      - "5000:5000"

volumes:
  postgres_data:
